spring.application.name=facturacion

spring.datasource.url=jdbc:sqlserver://163.178.173.130:1433;databaseName=SistemaFacturacionEmpresaPropi;encrypt=false
spring.datasource.username=basesdedatos
spring.datasource.password=BasesRP2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Turn off the Spring Boot banner
spring.main.banner-mode=off

# Reduce logging level
logging.level.root=warn

# Show JPA/Hibernate logging messages
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

# Context path
server.servlet.context-path=/facturacion
server.port=8084